# Generated by Django 4.0.4 on 2022-09-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Aryabhata', max_length=100),
        ),
    ]
